### ISSUE TITLE
Merge with ha-glocaltokens

### ISSUE THREAD

**Issue by leikoilja** [ArnyminerZ/HomeAssistant-GoogleHome#8]
Hey, @ArnyminerZ, I just found out that you are developing very similar packages as we do at https://github.com/leikoilja/ha-glocaltokens with @DurgNomis-drol. 
Do you want to join and merge our repos together? 
I will add you as a maintainer in the repo, so we would be much more efficient altogether with the more consistent flow of develop-test-review-release under the same project instead of various smaller similar projects.

Keeping it close to `glocaltoken` package will allow for both projects to grow faster with more contributors

**Comment by ArnyminerZ** [comment]
Of course! I'm already working with you 😄 my idea is to deprecate this repo slowly to move into yours.

**Comment by leikoilja** [comment]
Sounds amazing! Welcome to the team! 💥  Both me and @DurgNomis-drol are happy you ll be joining us 🚀  I will make you a collaborator on the repo as well. 

@ArnyminerZ, @DurgNomis-drol, I have also enabled some precautions dev features for the https://github.com/leikoilja/ha-glocaltokens repo like:
- We can't push to `master` without having a separate branch and creating PRs first. Pushing to `master` can only be done with `force`, only for hotfixes is something really needs to be fixed urgently. Apart from that let's all(incl me ofc) try to create PRs for each other and review them 💥
