### ISSUE TITLE
Issue w/ random Google Acct. Logouts

### ISSUE THREAD

**Issue by HIT2022** [ArnyminerZ/HomeAssistant-GoogleHome#9]
Hi @ArnyminerZ,

A while back you'd mentioned "Important notice: Right now I have encountered a problem with the script that kept logging me out from my Google Account on my Android phone when the script was ran. Doesn’t make any sense, so I’m working on it."

Did you have any luck in addressing this? Is it just related to the frequency with which your project is pulling down tokens/updates?

I'm eventually going to migrate to your combined leikoilja/ha-google-home implementation as soon as it is stable, but in the meantime I'm pulling alarms down via python scripts, and this logging out issue as has been giving me a headache. In my case I get logged out once every 3 days, and from all devices (Android, Google TV, etc.).

Thanks!

**Comment by ArnyminerZ** [comment]
Hi, this repository has been deprecated, and the work has been moved to [ha-google-home](https://github.com/leikoilja/ha-google-home). That repository shouldn't give any issues.
If you want to work with Python scripts, I recommend using the package we created called [glocaltokens](https://github.com/leikoilja/glocaltokens)
